services:
  rednil-web:
    image: rednil-web:latest
    container_name: rednil-web
    restart: unless-stopped
    networks:
      - cloudflared-tunnel
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  cloudflared-tunnel:
    external: true
